name: SBT / Scala - Release Pipe

on:
  workflow_dispatch:
    inputs:
      set_release_version:
        description: 'Set release version'
        required: true
        type: boolean
        default: true
      override_version:
        description: '(Override)'
        required: false
        type: string
      set_tag:
        description: 'Tag'
        required: true
        type: boolean
        default: true
      override_tag:
        description: '(Override)'
        required: false
        type: string

      set_next_version:
        description: 'Set next development version'
        required: true
        type: boolean
        default: true
      override_next_version:
        description: '(Override)'
        required: false
        type: string

      pkg:
        description: 'Package and sign artifacts'
        required: false
        type: choice
        options:
          - 'cross'
          - '2.12'
          - '2.13'
          - '3.1'
      pkg_check:
        description: '- Check dependencies'
        required: true
        type: boolean
        default: true
      pkg_test:
        description: '- Test'
        required: true
        type: boolean
        default: true
      pkg_maven:
        description: '- Package Maven Style'
        required: true
        type: boolean
        default: true
      pkg_sign:
        description: '- Sign'
        required: true
        type: boolean
        default: true
      module_core:
        description: 'Module: core'
        required: true
        type: boolean
        default: true
      module_akka:
        description: 'Module: akka'
        required: true
        type: boolean
        default: true
      module_fs2:
        description: 'Module: fs2'
        required: true
        type: boolean
        default: true
      module_noop:
        description: 'Module: noop'
        required: true
        type: boolean
        default: true
      module_jaeger:
        description: 'Module: jaeger'
        required: true
        type: boolean
        default: true
      module_compiler_plugin:
        description: 'Module: compiler-plugin'
        required: true
        type: boolean
        default: false

      publish_sonatype:
        description: 'Publish to Sonatype'
        required: true
        type: choice
        default: ''
        options:
          - ''
          - 'Release'
          - 'Promote to Release'
          - 'Staging'
          - 'Snapshot'

      publish_release:
        description: 'Publish on Github'
        required: true
        type: boolean
        default: false

permissions:
  contents: write

jobs:

  package_signed:
    name: 'Package and sign artifacts'
    runs-on: ubuntu-latest
#    steps:
#      - uses: actions/checkout@v3
#      - uses: git-actions/set-user@v1.0.0

#  check:
#    name: 'Step 1: Check dependencies'
#    if: ${{ inputs.step_check }}
#    runs-on: ubuntu-latest
#    steps:
#      - uses: actions/checkout@v3
#      #- uses: actions/cache@v3
#      #  with:
#      #    path: |
#      #      ~/.ivy2/cache
#      #      ~/.sbt
#      #      ~/work/opentracing-scala/opentracing-scala/
#      #
#      #    key: ${{ runner.os }}-sbt-${{ hashFiles('**/build.sbt') }}
#      - uses: coursier/cache-action@v6.3
#      - uses: VirtusLab/scala-cli-setup@main
#        with:
#          jvm: adopt:11
#      - # id: run
#        run: ./scripts/sbt-release-pipe.sh check "${{ inputs.module }}"
#    # outputs:
#    #   output1: ${{ steps.run.outputs.test }}
#    #   output2: ${{ steps.step2.outputs.test }}
