name: SBT / Scala - Release Pipe

on:
  workflow_dispatch:
    inputs:
      module:
        description: 'Run for single sbt sub-project'
        type: choice
        default: 'root+'
        options:
          - core
          - akka
          - fs2
          - noop
          - jaeger
          - root+
          - compiler-plugin
      step_check:
        description: 'Step 1: Check dependencies'
        type: boolean
        default: true
      step_compile:
        description: 'Step 2: Compile'
        type: boolean
        default: true
      step_test:
        description: 'Step 3: Test'
        type: boolean
        default: true
      step_release_version:
        description: 'Step 4: Set release version'
        type: boolean
        default: true
      override_version:
        description: '(Override)'
        required: false
        type: string
      step_tag:
        description: 'Step 4: Tag'
        type: boolean
        default: true
      override_tag:
        description: '(Override)'
        required: false
        type: string
      step_release:
        description: 'Step 5: Publish / Release'
        type: boolean
        default: true
      target:
        description: 'Publish target'
        required: true
        type: choice
        default: 'Staging'
        options:
          - 'Release'
          - 'Promote'
          - 'Staging'
          - 'Local Test'
      step_next_version:
        description: 'Step 6: Set next development version'
        type: boolean
        default: true
      override_next_version:
        description: '(Override)'
        required: false
        type: string
      step_push:
        description: 'Step 7: Push changes'
        type: boolean
        default: true

permissions:
  contents: write

jobs:
  check:
    name: '[${{ inputs.module }}] Step 1: Check dependencies'
    if: ${{ inputs.step_check }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      #- uses: actions/cache@v3
      #  with:
      #    path: |
      #      ~/.ivy2/cache
      #      ~/.sbt
      #      ~/work/opentracing-scala/opentracing-scala/
      #      
      #    key: ${{ runner.os }}-sbt-${{ hashFiles('**/build.sbt') }}
      - uses: coursier/cache-action@v6.3
      - uses: VirtusLab/scala-cli-setup@main
        with:
          jvm: adopt:11
      - # id: run
        run: ./scripts/sbt-release-pipe.sh check "${{ inputs.module }}"
    # outputs:
    #   output1: ${{ steps.run.outputs.test }}
    #   output2: ${{ steps.step2.outputs.test }}
